module.exports = {
  data: [
    {
      id: "449140",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2021-08-31T08:36:21.998-03:00",
        email: null,
        faxNumber: null,
        firstEmail: null,
        franchiseName: null,
        gdsPin: null,
        id: 449140,
        internalId: null,
        licenseNumber: null,
        name: "Lindsay Small",
        firstName: "Lindsay",
        lastName: "Small",
        officeName: "Main",
        organizationId: null,
        organizationName: null,
        payableName: "Lindsay Small",
        payableNameOption: "payable_to_name",
        phoneNumber: null,
        preventXeroSync: false,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2021-08-31T08:36:21.998-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2021-08-31T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5599773",
            type: "address",
          },
        },
        organization: {
          data: null,
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "449139",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2021-08-31T08:36:11.113-03:00",
        email: null,
        faxNumber: null,
        firstEmail: null,
        franchiseName: null,
        gdsPin: null,
        id: 449139,
        internalId: null,
        licenseNumber: null,
        name: "Erik Small",
        firstName: "Erik",
        lastName: "Small",
        officeName: "Main",
        organizationId: null,
        organizationName: null,
        payableName: "Erik Small",
        payableNameOption: "payable_to_name",
        phoneNumber: null,
        preventXeroSync: false,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2021-08-31T08:36:11.113-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2021-08-31T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5599772",
            type: "address",
          },
        },
        organization: {
          data: null,
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "449138",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2021-08-31T08:36:00.041-03:00",
        email: "susan.bishop49@bell.net",
        faxNumber: null,
        firstEmail: "susan.bishop49@bell.net",
        franchiseName: null,
        gdsPin: null,
        id: 449138,
        internalId: null,
        licenseNumber: null,
        name: "Susan Bishop",
        firstName: "Susan",
        lastName: "Bishop",
        officeName: "Main",
        organizationId: null,
        organizationName: null,
        payableName: "Susan Bishop",
        payableNameOption: "payable_to_name",
        phoneNumber: null,
        preventXeroSync: false,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2021-08-31T08:36:00.041-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2021-08-31T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5599771",
            type: "address",
          },
        },
        organization: {
          data: null,
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "260676",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2020-07-16T12:06:57.318-03:00",
        email: null,
        faxNumber: null,
        firstEmail: "frontdesk941@kw.com",
        franchiseName: null,
        gdsPin: null,
        id: 260676,
        internalId: null,
        licenseNumber: null,
        name: "Johnathan Drisdelle",
        firstName: "Johnathan",
        lastName: "Drisdelle",
        officeName: "Main",
        organizationId: 214203,
        organizationName: "Keller Williams Capital Realty",
        payableName: "Keller Williams Capital Realty",
        payableNameOption: "payable_to_organization_name",
        phoneNumber: null,
        preventXeroSync: true,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2022-03-21T13:39:52.332-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2020-07-16T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5261716",
            type: "address",
          },
        },
        organization: {
          data: {
            id: "214203",
            type: "organization",
          },
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "226038",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2020-04-27T15:33:10.438-03:00",
        email: null,
        faxNumber: null,
        firstEmail: "select@coldwellbanker.ca",
        franchiseName: null,
        gdsPin: null,
        id: 226038,
        internalId: null,
        licenseNumber: null,
        name: "Michelle Hardy",
        firstName: "Michelle",
        lastName: "Hardy",
        officeName: "Main",
        organizationId: 219122,
        organizationName: "Coldwell Banker Select",
        payableName: "Coldwell Banker Select",
        payableNameOption: "payable_to_organization_name",
        phoneNumber: null,
        preventXeroSync: false,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2022-03-21T13:39:45.037-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2020-04-27T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5200233",
            type: "address",
          },
        },
        organization: {
          data: {
            id: "219122",
            type: "organization",
          },
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "218682",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2020-03-31T10:03:10.177-03:00",
        email: null,
        faxNumber: null,
        firstEmail: "general.ylg@outlook.com",
        franchiseName: null,
        gdsPin: null,
        id: 218682,
        internalId: null,
        licenseNumber: null,
        name: "Marcus Beesley",
        firstName: "Marcus",
        lastName: "Beesley",
        officeName: "Main",
        organizationId: 212736,
        organizationName: "Youssef Law Group",
        payableName: "Youssef Law Group",
        payableNameOption: "payable_to_organization_name",
        phoneNumber: "5064722172",
        preventXeroSync: false,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2022-03-21T13:39:43.013-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2020-03-31T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5188061",
            type: "address",
          },
        },
        organization: {
          data: {
            id: "212736",
            type: "organization",
          },
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "212737",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: null,
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2020-03-12T13:45:04.736-03:00",
        email: "jack.ylg@outlook.com",
        faxNumber: null,
        firstEmail: "jack.ylg@outlook.com",
        franchiseName: null,
        gdsPin: null,
        id: 212737,
        internalId: null,
        licenseNumber: null,
        name: "Jack Youssef",
        firstName: "Jack",
        lastName: "Youssef",
        officeName: "Main",
        organizationId: 212736,
        organizationName: "Youssef Law Group",
        payableName: "Youssef Law Group",
        payableNameOption: "payable_to_organization_name",
        phoneNumber: "5064722172",
        preventXeroSync: false,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Profile",
        xeroSyncFrequency: "weekly",
        updatedAt: "2022-03-21T13:39:41.577-03:00",
        advertisingOptOutAt: null,
        landingPage: null,
        dailySummaryAt: "2020-03-12T20:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5177192",
            type: "address",
          },
        },
        organization: {
          data: {
            id: "212736",
            type: "organization",
          },
        },
        xeroContacts: {
          data: [],
        },
        offices: {
          data: [],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
    {
      id: "212649",
      type: "profile",
      attributes: {
        allowDirectPayout: false,
        annualGoal: "0.0",
        birthday: null,
        boardNumber: null,
        brokerageName: "The Right Choice Brokerage",
        businessNumber: null,
        cellNumber: null,
        corporateActiveAt: null,
        createdAt: "2020-03-12T11:24:32.388-03:00",
        email: "dave@therightchoicerealty.ca",
        faxNumber: null,
        firstEmail: "dave@therightchoicerealty.ca",
        franchiseName: "Independent",
        gdsPin: 100090,
        id: 212649,
        internalId: null,
        licenseNumber: null,
        name: "Dave Watt",
        firstName: "Dave",
        lastName: "Watt",
        officeName: "Main",
        organizationId: 469898,
        organizationName: "The Right Choice Realty Ltd.",
        payableName: "The Right Choice Realty Ltd.",
        payableNameOption: "payable_to_organization_name",
        phoneNumber: "",
        preventXeroSync: true,
        showDealSummary: false,
        taxFiling: true,
        taxNumber: null,
        type: "Agent",
        xeroSyncFrequency: "weekly",
        updatedAt: "2023-03-31T20:01:11.024-03:00",
        advertisingOptOutAt: null,
        landingPage: "deals",
        dailySummaryAt: "2020-03-12T16:00:00.000-03:00",
        dailySummaryLastSentAt: null,
        activeUser: false,
        company: false,
        agentInfosCount: 1,
      },
      relationships: {
        address: {
          data: {
            id: "5177052",
            type: "address",
          },
        },
        organization: {
          data: {
            id: "469898",
            type: "organization",
          },
        },
        xeroContacts: {
          data: [
            {
              id: "77483",
              type: "xeroContact",
            },
          ],
        },
        offices: {
          data: [
            {
              id: "419",
              type: "office",
            },
          ],
        },
        franchises: {
          data: [],
        },
        brokerages: {
          data: [],
        },
      },
    },
  ],
  included: [
    {
      id: "5599773",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: null,
        createdAt: "2021-08-31T08:36:22.009-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2021-08-31T08:36:22.009-03:00",
      },
    },
    {
      id: "5599772",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: null,
        createdAt: "2021-08-31T08:36:11.122-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2021-08-31T08:36:11.122-03:00",
      },
    },
    {
      id: "5599771",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: null,
        createdAt: "2021-08-31T08:36:00.052-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2021-08-31T08:36:00.052-03:00",
      },
    },
    {
      id: "5261716",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: null,
        createdAt: "2020-07-16T12:06:57.330-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2020-07-16T12:06:57.330-03:00",
      },
    },
    {
      id: "5200233",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: null,
        createdAt: "2020-04-27T15:33:10.455-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2020-04-27T15:33:10.455-03:00",
      },
    },
    {
      id: "5188061",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: null,
        createdAt: "2020-03-31T10:03:10.193-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2020-03-31T10:03:10.193-03:00",
      },
    },
    {
      id: "5177192",
      type: "address",
      attributes: {
        addressLineOne: null,
        addressLineTwo: null,
        city: null,
        country: "CAN",
        createdAt: "2020-03-12T13:45:04.752-03:00",
        postalCode: null,
        province: null,
        unit: null,
        updatedAt: "2020-03-12T13:45:04.752-03:00",
      },
    },
    {
      id: "5177052",
      type: "address",
      attributes: {
        addressLineOne: "288 Union St.",
        addressLineTwo: null,
        city: "Fredericton",
        country: null,
        createdAt: "2020-03-12T11:24:32.411-03:00",
        postalCode: "E3A 1E5",
        province: "New Brunswick",
        unit: null,
        updatedAt: "2022-01-27T11:09:22.466-04:00",
      },
    },
  ],
  meta: {
    count: 8,
  },
  links: {
    first:
      "https://api.loft47.com/v1/brokerages/310/profiles?filter%5Bids%5D=212649%2C226038%2C218682%2C212737%2C449140%2C+449139%2C449138%2C260676%2C212694&include=address&page%5Bnumber%5D=1",
    self: "https://api.loft47.com/v1/brokerages/310/profiles?filter%5Bids%5D=212649%2C226038%2C218682%2C212737%2C449140%2C+449139%2C449138%2C260676%2C212694&include=address&page%5Bnumber%5D=1",
    prev: "https://api.loft47.com/v1/brokerages/310/profiles?filter%5Bids%5D=212649%2C226038%2C218682%2C212737%2C449140%2C+449139%2C449138%2C260676%2C212694&include=address&page%5Bnumber%5D=1",
    next: "https://api.loft47.com/v1/brokerages/310/profiles?filter%5Bids%5D=212649%2C226038%2C218682%2C212737%2C449140%2C+449139%2C449138%2C260676%2C212694&include=address&page%5Bnumber%5D=1",
    last: "https://api.loft47.com/v1/brokerages/310/profiles?filter%5Bids%5D=212649%2C226038%2C218682%2C212737%2C449140%2C+449139%2C449138%2C260676%2C212694&include=address&page%5Bnumber%5D=1",
  },
};
